// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NewScriptTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void newScript() {
    driver.get("https://www.calculator.net/bmr-calculator.html/bmr-calculator.html");
    driver.manage().window().setSize(new Dimension(900, 600));
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.id("cage")).click();
    driver.findElement(By.id("cage")).sendKeys("18");
    driver.findElement(By.cssSelector("td > .cbcontainer:nth-child(1)")).click();
    driver.findElement(By.id("cheightmeter")).click();
    driver.findElement(By.id("cheightmeter")).sendKeys("170");
    driver.findElement(By.id("ckg")).click();
    driver.findElement(By.id("ckg")).sendKeys("70");
    driver.findElement(By.linkText("+ Settings")).click();
    driver.findElement(By.cssSelector("div > .cbcontainer:nth-child(2)")).click();
    driver.findElement(By.name("x")).click();
    vars.put("var1", driver.findElement(By.cssSelector("font > b")).getText());
    System.out.println(vars.get("var1").toString());
    System.out.println("The_test_string-> 01281727121");
  }
}
